# Generated by Django 3.2.3 on 2021-06-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_categoria_modelos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelos',
            new_name='Categoria',
        ),
    ]
