# Generated by Django 3.2.3 on 2021-06-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetos',
            new_name='Articulos',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Modelos',
        ),
    ]
