# Generated by Django 3.2.3 on 2021-06-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210621_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca del Articulo')),
                ('articulo', models.CharField(max_length=20, verbose_name='Articulo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Modelos',
            new_name='Categoria',
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.AddField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
