# Generated by Django 3.2.3 on 2021-06-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Modelos',
        ),
    ]
